services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: studenti
    volumes:
      - mysql1:/var/lib/mysql
    networks:
      - spring-network

  myapp:
    container_name: myapp
    image: primaapp
    ports:
      - 8082:8082
    networks:
      - spring-network
    depends_on:
      - mysql
networks:
  spring-network:
    driver: bridge

volumes:
  mysql1:



