name: Build & Deploy spring app
on: #definisce il trigger dell'azione
  push:
    branches:
      - master


jobs:
  build-deploy: #Nome del job
    name: build and deploy this app
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup jdk 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the app
        run: | #simbolo usato per introdurre più comandi
          mvn clean
          mvn -B package --file pom.xml

      - name: Build docker image
        uses: docker/build-push-action@v2
        with:
          context: . #Percorso del dockerfile per la build
          dockerfile: Dockerfile
          push: false #In questo step verifichiamo solo se siamo in grado di fare la build. Faremo la push successivamente
          tags:  ${{ secrets.DOCKER_HUB__USERNAME }}/freelancing:today #<dockerhub-username>/<repository-name>:<tag>

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB__USERNAME }}
          password: ${{ secrets.DOCKER_HUB__ACCESS_TOKEN }}

      - name: Push to docker Hub
        uses: docker/build-push-action@v2
        with:
          context: . #Percorso del dockerfile per la build
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB__USERNAME }}/freelancing:today
